In [1]:
import pandas as pd

In [2]:
customers_raw = pd.read_csv('../Data/customers.csv')
customers_raw

Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [3]:
customers = customers_raw.copy()

In [6]:
# handle missing values

customers.isna().any()

Name               False
Age                 True
Followers           True
Income             False
Sign Up Date       False
Discount           False
Education Level    False
dtype: bool

In [7]:
customers['Age'] = customers['Age'].fillna(customers['Age'].median())
customers['Followers'] = customers['Followers'].fillna(0)

In [9]:
# work on the 'Income' column

customers['Income']

0     45000
1     28000
2    120000
3    450000
4     75000
5     62000
6     81000
7     60000
Name: Income, dtype: int64

In [10]:
# work on the Age and Followers column

customers['Age'] = customers['Age'].astype(int)
customers['Followers'] = customers['Followers'].astype(int)

In [13]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Name             8 non-null      object
 1   Age              8 non-null      int64 
 2   Followers        8 non-null      int64 
 3   Income           8 non-null      int64 
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: int64(3), object(4)
memory usage: 580.0+ bytes


#### Change the date time datatype

In [14]:
customers['Sign Up Date']

0    5/18/23
1    8/23/23
2    4/25/23
3     5/5/23
4    6/14/23
5    8/26/23
6    9/24/23
7     9/8/23
Name: Sign Up Date, dtype: object

In [15]:
customers['Sign Up Date'] = pd.to_datetime(customers['Sign Up Date'], format = '%m/%d/%y')
customers['Sign Up Date']

0   2023-05-18
1   2023-08-23
2   2023-04-25
3   2023-05-05
4   2023-06-14
5   2023-08-26
6   2023-09-24
7   2023-09-08
Name: Sign Up Date, dtype: datetime64[ns]

#### Extracting the Datetime

In [16]:
customers['Sign up Month'] =customers['Sign Up Date'].dt.month

customers['Sign up Month']

0    5
1    8
2    4
3    5
4    6
5    8
6    9
7    9
Name: Sign up Month, dtype: int32

In [17]:
customers['Sign up DoW'] =customers['Sign Up Date'].dt.dayofweek

customers['Sign up DoW']

0    3
1    2
2    1
3    4
4    2
5    5
6    6
7    4
Name: Sign up DoW, dtype: int32

#### np.where()

In [18]:
import numpy as np

In [19]:
customers['Discount'] = np.where(customers['Discount']=='Yes', 1, 0)
customers['Discount']

0    1
1    1
2    0
3    0
4    1
5    0
6    0
7    0
Name: Discount, dtype: int64

### Dummy Variables

In [21]:
customers['Education Level']

0            College
1        High School
2    Graduate School
3            College
4        High School
5            College
6            College
7        High School
Name: Education Level, dtype: object

In [24]:
dummies_edu=pd.get_dummies(customers['Education Level']).astype(int)
dummies_edu

College  Graduate School  High School
0        1                0            0
1        0                0            1
2        0                1            0
3        1                0            0
4        0                0            1
5        1                0            0
6        1                0            0
7        0                0            1

In [25]:
# combine dfs
customers = pd.concat([customers, dummies_edu], axis = 1)
customers

Name  Age  Followers  Income Sign Up Date  Discount  Education Level  \
0     Aria   25          0   45000   2023-05-18         1          College   
1    Chord   19         12   28000   2023-08-23         1      High School   
2  Harmony   26          0  120000   2023-04-25         0  Graduate School   
3   Melody   47          0  450000   2023-05-05         0          College   
4     Reed   52          0   75000   2023-06-14         1      High School   
5   Selena   29          1   62000   2023-08-26         0          College   
6  Stefani   29          0   81000   2023-09-24         0          College   
7   Taylor   33         52   60000   2023-09-08         0      High School   

   Sign up Month  Sign up DoW  College  Graduate School  High School  
0              5            3        1                0            0  
1              8            2        0                0            1  
2              4            1        0                1            0  
3              5            4        1                0            0  
4              6            2        0                0            1  
5              8            5        1                0            0  
6              9            6        1                0            0  
7              9            4        0                0            1

### Feature engineering

In [26]:
songs_genres_dict = {'Customer': ['Aria', 'Chord', 'Harmony', 'Melody', 'Reed', 'Selena', 'Stefani', 'Taylor'],
                     '# Songs': [99, 51, 18, 2, 5, 60, 15, 121],
                     'Indie': [48, 36, 5, 0, 0, 20, 2, 19],
                     'Pop': [50, 15, 10, 0, 0, 20, 5, 89],
                     'Rock': [1, 0, 3, 2, 5, 20, 8, 13]}

songs_genres = pd.DataFrame(songs_genres_dict)
songs_genres

Customer  # Songs  Indie  Pop  Rock
0     Aria       99     48   50     1
1    Chord       51     36   15     0
2  Harmony       18      5   10     3
3   Melody        2      0    0     2
4     Reed        5      0    0     5
5   Selena       60     20   20    20
6  Stefani       15      2    5     8
7   Taylor      121     19   89    13

In [27]:
customers

Name  Age  Followers  Income Sign Up Date  Discount  Education Level  \
0     Aria   25          0   45000   2023-05-18         1          College   
1    Chord   19         12   28000   2023-08-23         1      High School   
2  Harmony   26          0  120000   2023-04-25         0  Graduate School   
3   Melody   47          0  450000   2023-05-05         0          College   
4     Reed   52          0   75000   2023-06-14         1      High School   
5   Selena   29          1   62000   2023-08-26         0          College   
6  Stefani   29          0   81000   2023-09-24         0          College   
7   Taylor   33         52   60000   2023-09-08         0      High School   

   Sign up Month  Sign up DoW  College  Graduate School  High School  
0              5            3        1                0            0  
1              8            2        0                0            1  
2              4            1        0                1            0  
3              5            4        1                0            0  
4              6            2        0                0            1  
5              8            5        1                0            0  
6              9            6        1                0            0  
7              9            4        0                0            1

In [28]:
model_df = pd.concat([customers, songs_genres], axis = 1).drop(columns = ['Customer'])

In [29]:
model_df

Name  Age  Followers  Income Sign Up Date  Discount  Education Level  \
0     Aria   25          0   45000   2023-05-18         1          College   
1    Chord   19         12   28000   2023-08-23         1      High School   
2  Harmony   26          0  120000   2023-04-25         0  Graduate School   
3   Melody   47          0  450000   2023-05-05         0          College   
4     Reed   52          0   75000   2023-06-14         1      High School   
5   Selena   29          1   62000   2023-08-26         0          College   
6  Stefani   29          0   81000   2023-09-24         0          College   
7   Taylor   33         52   60000   2023-09-08         0      High School   

   Sign up Month  Sign up DoW  College  Graduate School  High School  # Songs  \
0              5            3        1                0            0       99   
1              8            2        0                0            1       51   
2              4            1        0                1            0       18   
3              5            4        1                0            0        2   
4              6            2        0                0            1        5   
5              8            5        1                0            0       60   
6              9            6        1                0            0       15   
7              9            4        0                0            1      121   

   Indie  Pop  Rock  
0     48   50     1  
1     36   15     0  
2      5   10     3  
3      0    0     2  
4      0    0     5  
5     20   20    20  
6      2    5     8  
7     19   89    13

In [30]:
model_df['Pop_Pct'] = model_df['Pop']/model_df['# Songs']
model_df

Name  Age  Followers  Income Sign Up Date  Discount  Education Level  \
0     Aria   25          0   45000   2023-05-18         1          College   
1    Chord   19         12   28000   2023-08-23         1      High School   
2  Harmony   26          0  120000   2023-04-25         0  Graduate School   
3   Melody   47          0  450000   2023-05-05         0          College   
4     Reed   52          0   75000   2023-06-14         1      High School   
5   Selena   29          1   62000   2023-08-26         0          College   
6  Stefani   29          0   81000   2023-09-24         0          College   
7   Taylor   33         52   60000   2023-09-08         0      High School   

   Sign up Month  Sign up DoW  College  Graduate School  High School  # Songs  \
0              5            3        1                0            0       99   
1              8            2        0                0            1       51   
2              4            1        0                1            0       18   
3              5            4        1                0            0        2   
4              6            2        0                0            1        5   
5              8            5        1                0            0       60   
6              9            6        1                0            0       15   
7              9            4        0                0            1      121   

   Indie  Pop  Rock   Pop_Pct  
0     48   50     1  0.505051  
1     36   15     0  0.294118  
2      5   10     3  0.555556  
3      0    0     2  0.000000  
4      0    0     5  0.000000  
5     20   20    20  0.333333  
6      2    5     8  0.333333  
7     19   89    13  0.735537

### Binning


In [32]:
model_df['Sign up DoW']

0    3
1    2
2    1
3    4
4    2
5    5
6    6
7    4
Name: Sign up DoW, dtype: int32

In [33]:
model_df['Weekend'] = np.where(model_df['Sign up DoW'].isin([5,6]),1,0)
model_df['Weekend']

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    0
Name: Weekend, dtype: int64

### Proxy variables


In [34]:

# external data with the average temperature in F each month in Chicago
avg_temp_dict = {'Month': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                 'Avg_Temp': [32, 36, 45, 56, 66, 77, 82, 81, 74, 62, 50, 37]}

avg_temp = pd.DataFrame(avg_temp_dict)
avg_temp

Month  Avg_Temp
0       1        32
1       2        36
2       3        45
3       4        56
4       5        66
5       6        77
6       7        82
7       8        81
8       9        74
9      10        62
10     11        50
11     12        37

In [36]:
model_df['Sign up Month']

0    5
1    8
2    4
3    5
4    6
5    8
6    9
7    9
Name: Sign up Month, dtype: int32

In [37]:
pd.merge(model_df, avg_temp, left_on='Sign up Month', right_on='Month')

Name  Age  Followers  Income Sign Up Date  Discount  Education Level  \
0     Aria   25          0   45000   2023-05-18         1          College   
1    Chord   19         12   28000   2023-08-23         1      High School   
2  Harmony   26          0  120000   2023-04-25         0  Graduate School   
3   Melody   47          0  450000   2023-05-05         0          College   
4     Reed   52          0   75000   2023-06-14         1      High School   
5   Selena   29          1   62000   2023-08-26         0          College   
6  Stefani   29          0   81000   2023-09-24         0          College   
7   Taylor   33         52   60000   2023-09-08         0      High School   

   Sign up Month  Sign up DoW  College  Graduate School  High School  # Songs  \
0              5            3        1                0            0       99   
1              8            2        0                0            1       51   
2              4            1        0                1            0       18   
3              5            4        1                0            0        2   
4              6            2        0                0            1        5   
5              8            5        1                0            0       60   
6              9            6        1                0            0       15   
7              9            4        0                0            1      121   

   Indie  Pop  Rock   Pop_Pct  Weekend  Month  Avg_Temp  
0     48   50     1  0.505051        0      5        66  
1     36   15     0  0.294118        0      8        81  
2      5   10     3  0.555556        0      4        56  
3      0    0     2  0.000000        0      5        66  
4      0    0     5  0.000000        0      6        77  
5     20   20    20  0.333333        1      8        81  
6      2    5     8  0.333333        1      9        74  
7     19   89    13  0.735537        0      9        74

In [38]:
model_df = pd.merge(model_df, avg_temp, left_on='Sign up Month', right_on='Month').drop(columns = ['Month'])

In [39]:
model_df

Name  Age  Followers  Income Sign Up Date  Discount  Education Level  \
0     Aria   25          0   45000   2023-05-18         1          College   
1    Chord   19         12   28000   2023-08-23         1      High School   
2  Harmony   26          0  120000   2023-04-25         0  Graduate School   
3   Melody   47          0  450000   2023-05-05         0          College   
4     Reed   52          0   75000   2023-06-14         1      High School   
5   Selena   29          1   62000   2023-08-26         0          College   
6  Stefani   29          0   81000   2023-09-24         0          College   
7   Taylor   33         52   60000   2023-09-08         0      High School   

   Sign up Month  Sign up DoW  College  Graduate School  High School  # Songs  \
0              5            3        1                0            0       99   
1              8            2        0                0            1       51   
2              4            1        0                1            0       18   
3              5            4        1                0            0        2   
4              6            2        0                0            1        5   
5              8            5        1                0            0       60   
6              9            6        1                0            0       15   
7              9            4        0                0            1      121   

   Indie  Pop  Rock   Pop_Pct  Weekend  Avg_Temp  
0     48   50     1  0.505051        0        66  
1     36   15     0  0.294118        0        81  
2      5   10     3  0.555556        0        56  
3      0    0     2  0.000000        0        66  
4      0    0     5  0.000000        0        77  
5     20   20    20  0.333333        1        81  
6      2    5     8  0.333333        1        74  
7     19   89    13  0.735537        0        74

### Scaling

In [40]:
# normalization
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()

In [41]:
model_subset = model_df[['Age', '# Songs', 'Pop_Pct']]
model_subset

Age  # Songs   Pop_Pct
0   25       99  0.505051
1   19       51  0.294118
2   26       18  0.555556
3   47        2  0.000000
4   52        5  0.000000
5   29       60  0.333333
6   29       15  0.333333
7   33      121  0.735537

In [42]:
mm_scaler.fit(model_subset)

MinMaxScaler()

In [43]:
mm_scaler.data_min_

array([19.,  2.,  0.])

In [44]:
mm_scaler.data_max_

array([ 52.        , 121.        ,   0.73553719])

In [45]:
mm_scaler.data_range_

array([ 33.        , 119.        ,   0.73553719])

In [46]:
mm_scaler.transform(model_subset)

array([[0.18181818, 0.81512605, 0.6866417 ],
       [0.        , 0.41176471, 0.39986781],
       [0.21212121, 0.13445378, 0.75530587],
       [0.84848485, 0.        , 0.        ],
       [1.        , 0.02521008, 0.        ],
       [0.3030303 , 0.48739496, 0.45318352],
       [0.3030303 , 0.1092437 , 0.45318352],
       [0.42424242, 1.        , 1.        ]])

In [47]:
# fit and transform

mm_scaler.fit_transform(model_subset)

array([[0.18181818, 0.81512605, 0.6866417 ],
       [0.        , 0.41176471, 0.39986781],
       [0.21212121, 0.13445378, 0.75530587],
       [0.84848485, 0.        , 0.        ],
       [1.        , 0.02521008, 0.        ],
       [0.3030303 , 0.48739496, 0.45318352],
       [0.3030303 , 0.1092437 , 0.45318352],
       [0.42424242, 1.        , 1.        ]])

In [ ]:
# standardization
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

In [51]:
model_subset.describe()

Age     # Songs   Pop_Pct
count   8.000000    8.000000  8.000000
mean   32.500000   46.375000  0.344616
std    11.313708   44.746708  0.257288
min    19.000000    2.000000  0.000000
25%    25.750000   12.500000  0.220588
50%    29.000000   34.500000  0.333333
75%    36.500000   69.750000  0.517677
max    52.000000  121.000000  0.735537

In [49]:
std_scaler.fit(model_subset)

StandardScaler()

In [50]:
std_scaler.mean_

array([32.5       , 46.375     ,  0.34461595])

In [52]:
std_scaler.var_

array([1.12000000e+02, 1.75198438e+03, 5.79223949e-02])

In [53]:
std_scaler.transform(model_subset)

array([[-0.70868339,  1.25726549,  0.66661437],
       [-1.2756301 ,  0.11049602, -0.20982319],
       [-0.61419227, -0.677908  ,  0.87646562],
       [ 1.37012121, -1.06016449, -1.4318981 ],
       [ 1.84257681, -0.98849139, -1.4318981 ],
       [-0.33071891,  0.32551529, -0.04687987],
       [-0.33071891, -0.74958109, -0.04687987],
       [ 0.04724556,  1.78286816,  1.62429915]])

In [54]:
# all in one step
std_scaler.fit_transform(model_subset)

array([[-0.70868339,  1.25726549,  0.66661437],
       [-1.2756301 ,  0.11049602, -0.20982319],
       [-0.61419227, -0.677908  ,  0.87646562],
       [ 1.37012121, -1.06016449, -1.4318981 ],
       [ 1.84257681, -0.98849139, -1.4318981 ],
       [-0.33071891,  0.32551529, -0.04687987],
       [-0.33071891, -0.74958109, -0.04687987],
       [ 0.04724556,  1.78286816,  1.62429915]])