# Cosine similarity

In [1]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [2]:
df= pd.read_csv('../Data/fruit_nutrition.csv')
df = df.set_index('fruit_100g')

In [3]:
df

energy_kcal  water_g  protein_g  totalfat_g  fiber_g  sugars_g  \
fruit_100g                                                                   
Banana               89     74.9       1.09        0.33      2.6     12.20   
Lemon                29     89.0       1.10        0.30      2.8      2.50   
Lime                 30     88.3       0.70        0.20      2.8      1.69   
Mango                46     88.3       0.91        0.27      1.5      8.39   
Peach                60     83.5       0.82        0.38      1.6     13.70   
Pineapple            50     86.0       0.54        0.12      1.4      9.85   

            vitaminc_mg  
fruit_100g               
Banana              8.7  
Lemon              53.0  
Lime               29.1  
Mango               4.1  
Peach              36.4  
Pineapple          47.8

In [4]:
df.index.name = None

In [5]:
df

energy_kcal  water_g  protein_g  totalfat_g  fiber_g  sugars_g  \
Banana              89     74.9       1.09        0.33      2.6     12.20   
Lemon               29     89.0       1.10        0.30      2.8      2.50   
Lime                30     88.3       0.70        0.20      2.8      1.69   
Mango               46     88.3       0.91        0.27      1.5      8.39   
Peach               60     83.5       0.82        0.38      1.6     13.70   
Pineapple           50     86.0       0.54        0.12      1.4      9.85   

           vitaminc_mg  
Banana             8.7  
Lemon             53.0  
Lime              29.1  
Mango              4.1  
Peach             36.4  
Pineapple         47.8

In [6]:
df = df.iloc[:, 5:]
df.shape

(6, 2)

In [7]:
df.loc[['Banana', 'Mango']]

sugars_g  vitaminc_mg
Banana     12.20          8.7
Mango       8.39          4.1

In [8]:
cosine_similarity(df.loc[['Banana', 'Mango']])


array([[1.       , 0.9864306],
       [0.9864306, 1.       ]])

In [9]:
cosine_similarity(df.loc[['Banana', 'Mango']])[0]

array([1.       , 0.9864306])

In [10]:
cos_matrix = cosine_similarity(df)

In [11]:
cos_matrix

array([[1.        , 0.61832414, 0.62683477, 0.9864306 , 0.83018982,
        0.73298243],
       [0.61832414, 1.        , 0.99994086, 0.48090193, 0.95146351,
        0.98784307],
       [0.62683477, 0.99994086, 1.        , 0.49040872, 0.95475426,
        0.98947527],
       [0.9864306 , 0.48090193, 0.49040872, 1.        , 0.72739811,
        0.61135407],
       [0.83018982, 0.95146351, 0.95475426, 0.72739811, 1.        ,
        0.98773952],
       [0.73298243, 0.98784307, 0.98947527, 0.61135407, 0.98773952,
        1.        ]])

In [46]:
# show array in one line

import numpy as np

np.set_printoptions(linewidth = np.inf)

In [47]:
cos_matrix

array([[1.        , 0.61832414, 0.62683477, 0.9864306 , 0.83018982,
        0.73298243],
       [0.61832414, 1.        , 0.99994086, 0.48090193, 0.95146351,
        0.98784307],
       [0.62683477, 0.99994086, 1.        , 0.49040872, 0.95475426,
        0.98947527],
       [0.9864306 , 0.48090193, 0.49040872, 1.        , 0.72739811,
        0.61135407],
       [0.83018982, 0.95146351, 0.95475426, 0.72739811, 1.        ,
        0.98773952],
       [0.73298243, 0.98784307, 0.98947527, 0.61135407, 0.98773952,
        1.        ]])

In [12]:
cos_df = pd.DataFrame(cos_matrix, index = df.index, columns = df.index)
cos_df

Banana     Lemon      Lime     Mango     Peach  Pineapple
Banana     1.000000  0.618324  0.626835  0.986431  0.830190   0.732982
Lemon      0.618324  1.000000  0.999941  0.480902  0.951464   0.987843
Lime       0.626835  0.999941  1.000000  0.490409  0.954754   0.989475
Mango      0.986431  0.480902  0.490409  1.000000  0.727398   0.611354
Peach      0.830190  0.951464  0.954754  0.727398  1.000000   0.987740
Pineapple  0.732982  0.987843  0.989475  0.611354  0.987740   1.000000

In [13]:
nutrition= pd.read_csv('../Data/fruit_nutrition.csv')
nutrition = nutrition.set_index('fruit_100g')

In [14]:
nutrition.index.name = None

In [15]:
nutrition

energy_kcal  water_g  protein_g  totalfat_g  fiber_g  sugars_g  \
Banana              89     74.9       1.09        0.33      2.6     12.20   
Lemon               29     89.0       1.10        0.30      2.8      2.50   
Lime                30     88.3       0.70        0.20      2.8      1.69   
Mango               46     88.3       0.91        0.27      1.5      8.39   
Peach               60     83.5       0.82        0.38      1.6     13.70   
Pineapple           50     86.0       0.54        0.12      1.4      9.85   

           vitaminc_mg  
Banana             8.7  
Lemon             53.0  
Lime              29.1  
Mango              4.1  
Peach             36.4  
Pineapple         47.8

In [16]:
cos_matrix_all = cosine_similarity(nutrition)
cos_df_all = pd.DataFrame(cos_matrix_all, index = nutrition.index, columns = nutrition.index)

cos_df_all

Banana     Lemon      Lime     Mango     Peach  Pineapple
Banana     1.000000  0.771868  0.834125  0.924742  0.936768   0.879313
Lemon      0.771868  1.000000  0.977395  0.876507  0.941340   0.978065
Lime       0.834125  0.977395  1.000000  0.952821  0.954719   0.969866
Mango      0.924742  0.876507  0.952821  1.000000  0.945803   0.918046
Peach      0.936768  0.941340  0.954719  0.945803  1.000000   0.989721
Pineapple  0.879313  0.978065  0.969866  0.918046  0.989721   1.000000

In [17]:
# wrap in a function
def recommend_fruits(fruit_name, similarity_df):
    if fruit_name not in similarity_df.index:
        return f'{fruit_name} is not found in the fruit list'
    return similarity_df[[fruit_name]].sort_values(by = fruit_name, ascending = False)
 

In [18]:
recommend_fruits('Mango', cos_df_all)

Mango
Mango      1.000000
Lime       0.952821
Peach      0.945803
Banana     0.924742
Pineapple  0.918046
Lemon      0.876507

In [19]:
recommend_fruits('Apple', cos_df_all)

'Apple is not found in the fruit list'